! ***********************************************************************************
! * Copyright (C) 2021-2022 International Atomic Energy Agency (IAEA)               *
! *-----------------------------------------------------------------------------    *
! * Permission is hereby granted, free of charge, to any person obtaining a copy    *
! * of this software and associated documentation files (the "Software"), to deal   *
! * in the Software without restriction, including without limitation the rights    *
! * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell       *
! * copies of the Software, and to permit persons to whom the Software is furnished *
! * to do so, subject to the following conditions:                                  *
! *                                                                                 *
! * The above copyright notice and this permission notice shall be included in all  *
! * copies or substantial portions of the Software.                                 *
! *                                                                                 *
! * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR      *
! * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,        *
! * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE     *
! * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER          *
! * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,   *
! * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN       *
! * THE SOFTWARE.                                                                   *
! *                                                                                 *
! *-----------------------------------------------------------------------------    *
! *   AUTHOR:                                                                       *
! *   Viktor Zerkin, PhD                                                            *
! *   e-mail: V.Zerkin@iaea.org                                                     *
! *   International Atomic Energy Agency                                            *
! *   Nuclear Data Section, P.O.Box 100                                             *
! *   Wagramerstrasse 5, Vienna A-1400, AUSTRIA                                     *
! *   Phone: +43 1 2600 21714; Fax: +43 1 26007                                     *
! *                                                                                 *
! ***********************************************************************************

!gfortran sig1toc4.f sql1sub.c sqlite3.c -o sig1toc4
!gfortran sig1toc4.f sql1sub.c sqlite3.c -o sig1toc4.exe -pthread -ldl
!sig1toc4.exe >sig1toc4.tto.txt

	program sig1toc4
	character*512  dbname
	character*512  outfile/'sql1tmp.dat'/
	character*4096 sql
	character*10 dat,tim
	character*19 datim

        write (*,*) 'Program: sig1toc4.f (ver.2022-08-26)'
        write (*,*) 'Author:  V.Zerkin, IAEA-NDS, 2021-2022'
        write (*,*) 'Purpose: get CS data from X4Pro and output to C4'

	call date_and_time(DATE=dat,TIME=tim)
	write(datim,'(a,1h-,a,1h-,a,1h,,a,1h:,a,1h:,a)')
     1  dat(1:4),dat(5:6),dat(7:8),tim(1:2),tim(3:4),tim(5:6)
	write(*,'(a,a)')' Running: ',datim
        write (*,*)

	dbname='C:\projects\zerkin\pdev\x4sqlite1.db'
	dbname='../../x4sqlite1.db'

	ierr=ix4lite_open(trim(dbname)//char(0)) !--- char(0) added for compatibility with C
	if (ierr.ne.0) then
	    write (*,*) 'Cant open database'
	    stop
	endif

	write (*,*) 'Open database: ',trim(dbname),' ierr=',ierr
        write (*,*)

!	call getX4SqlSearch_SIG(sql,'Mn-55','n,a')
	call getX4SqlSearch_SIG_MT(sql,'Mn-55',107)
	write (*,*) 'SQL command:'
	write (*,*) trim(sql)

	sql=trim(sql)//char(0)
	outfile=trim(outfile)//char(0)
	ipnt=ix4lite_exec(sql,outfile)
	if (ierr.lt.0) then
	    write (*,*) 'SQL error ierr=',ipnt
	else
	    write (*,*) 'Operation done successfully:',ipnt,' points'
	endif
	call read_data(outfile,ipnt,'sig1toc4.c4')

	call ix4lite_close();

	write(*,'(/a)') 'Program completed successfully'
	stop
	end


	subroutine read_data(infile,ipnt,outfile)
	character(len=*) infile,outfile
	character*132 line,nam,val,fullCode,nowTrace,lastTrace
	character*9   DatasetID
	character*4   sYear,i78,sProd,sTarg
	character*12  Author1,Author1Ini
	character*25  Refer
	character*10  Target,Projectile
	dimension     c4data(8)
        CHARACTER*9   r4tostr9
	i78=' '
	xx=-1.
	r4nan=sqrt(xx) ! NaN
	write (*,*) 'Read data points:',ipnt
	nin=100
	open(unit=nin,file=infile,status='old',err=9999)
	nout=101
	open(unit=nout,file=outfile,status='unknown',err=9999)
	write(nout,'(a,a,a)')
     1	'#File ',trim(outfile),' generated by program sig1toc4.f'
	iDataset=0
	iipnt=0
	lastTrace=''
	do
	    read(nin,'(a12,a)',end=8888) nam,line
	    if (nam.eq.'//EOF')       exit
	    if (nam.eq.'$DatasetID')  DatasetID=line
	    if (nam.eq.'$fullCode')   fullCode=line
	    if (nam.eq.'$YearRef1')   read(line,'(i11)') iYear
	    if (nam.eq.'$YearRef1')   sYear=line
	    if (nam.eq.'$Author1')    Author1=line
	    if (nam.eq.'$Author1Ini') Author1Ini=line
	    if (nam.eq.'$nAuthors')   read(line,'(i11)')   nAuthors
	    if (nam.eq.'$iPoint')     read(line,'(i11)')   iPoint
	    if (nam.eq.'$En')         read(line,'(e15.0)') c4data(1)
	    if (nam.eq.'$dEn')        read(line,'(e15.0)') c4data(2)
	    if (nam.eq.'$Sig')        read(line,'(e15.0)') c4data(3)
	    if (nam.eq.'$dSig')       read(line,'(e15.0)') c4data(4)
	    if (nam.eq.'$MF')         read(line,'(i11)')   MF
	    if (nam.eq.'$MT')         read(line,'(i11)')   MT
	    if (nam.eq.'$zaTarget1')  read(line,'(i11)') izaTarget
	    if (nam.eq.'$zaIncident1')read(line,'(i11)') izaProjectile
	    if (nam.eq.'$sTarg')      sTarg=line
	    if (nam.eq.'$sProd')      sProd=line
	    if (nam.eq.'$Target')     Target=line
	    if (nam.eq.'$Projectile') Projectile=line
	    if (nam(1:4).eq.'####') then !--- Begin of new Datapoint
		iipnt=iipnt+1
		DatasetID=''
		fullCode=''
		iYear=0
		sYear='----'
		Author1=''
		Author1Ini=''
		nAuthors=0
		iPoint=-1
		MF=-1
		MT=-1
		izaTarget=0
		izaProjectile=0
		sTarg=''
		sProd=''
		Projectile=''
		do i=1,8
		    c4data(i)=r4nan
		enddo
		cycle
	    endif
	    if (nam.eq.'//') then !--- End of Datapoint
		write(nowTrace,*) trim(fullCode),' #',DatasetID
		if (nowTrace.ne.lastTrace) then
		    iDataset=iDataset+1
		    write(nout,'(/a,a,a,a,a,a,a,a,a,a,a,a,a)')
     1			  '#',DatasetID
     1			,' #',trim(Projectile),' #',trim(Target)
     1			,' #',sYear,',',trim(Author1Ini),trim(Author1)
     1			,' #',trim(fullCode)
		    write(nout,1001)
		    write(nout,1002)
		    write(*,*) '---Dataset---',trim(nowTrace)
		    lastTrace=nowTrace
		endif
		write(*,*) iipnt,iPoint,' X:',c4data(1),c4data(2)
     1		,' Y:',c4data(3),c4data(4)
!		Refer=trim(Author1Ini)//trim(Author1)//' ('//sYear//')'
		Refer=trim(Author1Ini)//trim(Author1)
!		if (nAuthors>1) Refer=trim(Refer)//',+'
		if (nAuthors>1) Refer=trim(Refer)//',et.al.'
!		Refer=trim(Refer)//'('//sYear(3:4)//')'
		Refer(22:25)='('//sYear(3:4)//')'
		write(nout,1100) izaProjectile,izaTarget,sTarg
     1		,MF,MT,sProd,' ',' ',(r4tostr9(c4data(i)),i=1,8)
     1		,i78,Refer,DatasetID
	    endif
	enddo
8888	close(nin)
	close(nout)
	write(*,*)'Total Datasets:',iDataset
9999	return
1100	format(I5,I6,A1,I3,I4,3A1,8A9,A3,A25,A9)
1001    format('#Proj Targ M MF MT PXC   Energy  dEnergy     Da'
     1  ,'ta   dData Cos/LO/ZP dCos/LO/AP LVL/HL dLVL/HL I78 Re'
     1  ,'fer (YY)              EntrySubP')
1002    format('#---><---->o<-><-->ooo<-------><-------><------'
     1  '-><-------><-------><-------><-------><-------><-><---'
     1  '--------------------><---><->o')
	end


	subroutine getX4SqlSearch_SIG(sql,target,react)
	character*4096 sql
	character(len=*) target,react
	sql=''
     1	//'select * from sig1                    '//char(10)
     1	//' where (Target like '''//target//''') '//char(10)
     1	//' and (Reaction like '''//react//''')  '//char(10)
	return
	end

	subroutine getX4SqlSearch_SIG_MT(sql,target,MT)
	character*4096 sql
	character(len=*) target
	write(sql,'(a,a,a,a,a,i4,a)') 'select * from sig1'
     1	,' where (Target like ''',target,''')'
     1	,' and (MT=',MT,')'
	return
	end

	function r4tostr9(rr4)
!	convert real*4 to character*9
!	author:  V.Zerkin, IAEA-NDS, 2022-09-04
	character*9  r4tostr9
	character*15 c15
	r4tostr9=' '
	if (isnan(rr4)) return
	if (rr4.ge.0) then
	    write(c15,'(1p,e12.5)') rr4
	    c15=c15(2:15)
	    if (c15(10:10).eq.'0') then
	 	c15(10:14)=c15(11:15) !0
	 	c15(8:14)=c15(9:15)   !E
	    else
		write(c15,'(1p,e11.4)') rr4
		c15=c15(2:15)
	 	c15(7:14)=c15(8:15)   !E
	    endif
	else
	    write(c15,'(1p,e11.4)') rr4
	    if (c15(10:10).eq.'0') then
	 	c15(10:14)=c15(11:15) !0
	 	c15(8:14)=c15(9:15)   !E
	    else
		write(c15,'(1p,e10.3)') rr4
	 	c15(7:14)=c15(8:15)   !E
	    endif
	endif
!	write(*,*) 'r4tostr9: rr4=',rr4,' c15:[',c15,']'
	if (c15(8:9).eq.'+0') c15(8:9)='  '
	r4tostr9=c15(1:9)
	return
	end
